<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AKHIL-TS" name="com.Home.Associate_Login" tests="7" failures="0" timestamp="5 Oct 2018 13:12:44 GMT" time="11.224" errors="1">
  <testcase name="TCBA01002" time="0.570" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01003" time="0.438" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01006" time="3.610" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01005" time="2.560" classname="com.Home.Associate_Login">
    <error type="java.lang.AssertionError" message="failed to assert text  Username was not found. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: failed to assert text  Username was not found. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.Home.Associate_Login.TCBA01005(Associate_Login.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- TCBA01005 -->
  <testcase name="TCBA01004" time="0.421" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01009" time="3.473" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01001" time="0.152" classname="com.Home.Associate_Login"/>
</testsuite> <!-- com.Home.Associate_Login -->
