<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vofox-Sebastian" name="com.Home.Associate_Login" tests="7" failures="0" timestamp="10 Oct 2018 12:44:43 GMT" time="11.488" errors="1">
  <testcase name="TCBA01003" time="0.470" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01002" time="0.865" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01004" time="0.469" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01001" time="0.022" classname="com.Home.Associate_Login">
    <error type="java.lang.AssertionError" message="expected [Log In | 5-15] but found [IGL]">
      <![CDATA[java.lang.AssertionError: expected [Log In | 5-15] but found [IGL]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.Home.Associate_Login.TCBA01001(Associate_Login.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TCBA01001 -->
  <testcase name="TCBA01005" time="2.522" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01009" time="3.586" classname="com.Home.Associate_Login"/>
  <testcase name="TCBA01006" time="3.554" classname="com.Home.Associate_Login"/>
</testsuite> <!-- com.Home.Associate_Login -->
